# Generated by Django 4.1.3 on 2023-03-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="women",
            options={
                "ordering": ["id"],
                "verbose_name": "Известные женщины",
                "verbose_name_plural": "Известные женщины",
            },
        ),
    ]
